---
title: "Test and example run for mixFine"
# author: Yanyu Liang
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup}
rm(list = ls())
library(dplyr)
library(ggplot2)
library(cowplot)
library(tictoc)
source('https://gist.githubusercontent.com/liangyy/43912b3ecab5d10c89f9d4b2669871c9/raw/8151c6fe70e3d4ee43d9ce340ecc0eb65172e616/my_ggplot_theme.R')
th = theme_bw(base_size = 15) + th 
```

```{r install_mixqtl}
devtools::install_github('liangyy/mixqtl', auth_token = '163286e54308901bcc73ac6cce9c03d3a8055e7c')
```

# Load data and package

```{r load_data}
library(mixqtl)
dat = readRDS('/Users/yanyul/Desktop/mixqtl-test/mixfine/input--ENSG00000277734.rds')
covariates = read.table('/Users/yanyul/Desktop/mixqtl-test/share_with_francois/covariate-combined.txt', header = T, stringsAsFactors = F)
covariate_names = stringr::str_replace(colnames(covariates), '\\.', '-')
covariates = cbind(covariates[, 1], covariates[, match(colnames(dat$geno1), as.character(covariate_names))])
indiv_offset = regress_against_covariate(dat$trc_g, dat$nlib, covariates)
geno1 = t(dat$geno1)
geno2 = t(dat$geno2)
class(geno1) = 'numeric'
class(geno2) = 'numeric'

df = data.frame(y1 = dat$ase1_g, y2 = dat$ase2_g, ytotal = dat$trc_g, lib_size = dat$nlib)

tic('run mixFine: ')
mod = mixfine(geno1, geno2, df$y1, df$y2, df$ytotal, df$lib_size, cov_offset = indiv_offset, trc_cutoff = 100, asc_cutoff = 50, weight_cap = 10, asc_cap = 1000)
toc()

if('cs' %in% names(mod)) {
  cs = mod$cs
  vars = mod$vars
  vars$variant_id = dat$geno_name[vars$variable]
} else {
  vars = summary(mod)$vars
  vars$variant_id = dat$geno_name[vars$variable]
  cs = summary(mod)$cs
}
```

# Load results generated from previous script

Previous script: [link](https://github.com/liangyy/project-ase/blob/master/test_scripts/gtex-v8-pipeline/scripts/run_mixfine.R)

## See 95% CS

```{r }
df = read.table('/Users/yanyul/Desktop/mixqtl-test/mixfine/result_pip-mixfine.ENSG00000277734.txt.gz', header = T, stringsAsFactors = F)
df2 = inner_join(df %>% select(-variable), vars %>% select(-variable), by = c('variant_id'), suffix = c('.old', '.mixqtl'))
head(df2 %>% select(variant_id, cs.old, cs.mixqtl))
```

## Plot PIP

```{r plot}
df2 %>% ggplot() + geom_point(aes(x = variable_prob.old, y = variable_prob.mixqtl), alpha = .1) + scale_x_log10() + scale_y_log10() + coord_equal() + th
```


# Session information

```{r sinfo}
sessionInfo()
```

