---
title: "Test and example run for mixQTL"
# author: Yanyu Liang
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup}
rm(list = ls())
library(dplyr)
library(ggplot2)
library(cowplot)
source('https://gist.githubusercontent.com/liangyy/43912b3ecab5d10c89f9d4b2669871c9/raw/8151c6fe70e3d4ee43d9ce340ecc0eb65172e616/my_ggplot_theme.R')
th = theme_bw(base_size = 15) + th 
```

```{r install_mixqtl}
devtools::install_github('liangyy/mixqtl', auth_token = '163286e54308901bcc73ac6cce9c03d3a8055e7c')
```

# Load data and package

```{r load_data}
library(mixqtl)
dat = readRDS('/Users/yanyul/Desktop/mixqtl-test/share_with_francois/example-input.ENSG00000002834.1.rds')
covariates = read.table('/Users/yanyul/Desktop/mixqtl-test/share_with_francois/covariate-combined.txt', header = T, stringsAsFactors = F)
covariate_names = stringr::str_replace(colnames(covariates), '\\.', '-')
covariates = cbind(covariates[, 1], covariates[, match(colnames(dat$geno1_b), as.character(covariate_names))])
x1 = as.numeric(dat$geno1_b)
x2 = as.numeric(dat$geno2_b)
indiv_offset = regress_against_covariate(dat$trc_g, dat$nlib, covariates)
geno1 = t(dat$geno1_b)
geno2 = t(dat$geno2_b)
class(geno1) = 'numeric'
class(geno2) = 'numeric'
is_na = is.na(geno1) | is.na(geno2)
geno1 = impute_geno(geno1)
geno2 = impute_geno(geno2)

df = data.frame(y1 = dat$ase1_g, y2 = dat$ase2_g, trc = dat$trc_g, Ti_lib = dat$nlib) %>% mutate(y_trc = trc, lib_size = Ti_lib, cov_offset = indiv_offset, y_ase1 = y1, y_ase2 = y2)
# mutate(y_trc = log(trc / Ti_lib / 2) - indiv_offset, y_ase = log(y1 / y2)) 

trc_g = (geno1 + geno2) / 2
ase_g = geno1 - geno2
ase_g[is_na] = 0

trc_estimate = matrix_ls_trc(df$y_trc, df$lib_size, trc_g, indiv_offset, trc_cutoff = 100)
ase_estimate = matrix_ls_asc(df$y_ase1, df$y_ase2, ase_g, asc_cutoff = 50, weight_cap = 10, asc_cap = 1000)

meta_result = meta_analyze(trc_estimate, ase_estimate)
meta_list = list()
for(i in names(meta_result)) {
  d = as.data.frame(lapply(meta_result[[i]], t))
  colnames(d) = paste0(colnames(d), '.', i)
  meta_list[[length(meta_list) + 1]] = d
}
merge = do.call(cbind, meta_list)
merge$variant_id = dat$geno_name
```

# Load results generated from previous script

Previous script: [link](https://github.com/liangyy/project-ase/blob/master/test_scripts/gtex-v8-pipeline/scripts/mixqtl_batch.R)

## Check difference

```{r load_previous}
df = read.table('/Users/yanyul/Desktop/mixqtl-test/share_with_francois/example-ENSG00000002834.mixqtl.txt.gz', header = T, stringsAsFactors = F)
for(i in 1 : ncol(df)) {
  if(is.character(df[1, i])) {
    next
  }
  message('check diff, sum(abs diff), of column ', colnames(df)[i], ': ' , sum(abs(df[, i] - merge[, i])))
}
```

## Plot significance

```{r plot}
df2 = inner_join(df, merge, by = 'variant_id', suffix = c('.old', '.mixqtl'))
plist = list()
for(i in c('trc', 'asc', 'meta')) {
  plist[[length(plist) + 1]] = df2 %>% ggplot() + geom_point(aes_string(x = paste0('bhat.', i, '.old'), y = paste0('bhat.', i, '.mixqtl')), alpha = .1) + th  + coord_equal()
}
for(i in c('trc', 'asc', 'meta')) {
  plist[[length(plist) + 1]] = df2 %>% ggplot() + geom_point(aes_string(x = paste0('pval.', i, '.old'), y = paste0('pval.', i, '.mixqtl')), alpha = .1) + scale_x_log10() + scale_y_log10() + th + coord_equal()
}
plot_grid(plotlist = plist)
```

# Session information

```{r sinfo}
sessionInfo()
```

